### PR TITLE
Azure Blob Storage Writer

### LINKED ISSUE #89: As a User, I can write data to Azure Blob Storage
WHY
In order to directly transfer raw data in Microsoft Azure Cloud.

HOW
Develop an Azure Blob writer in NCK

### PR DESCRIPTION
**Pull request by pol-defont-reaulx**
### Issue

- My PR resolves #89 

### Description

- Add Azure Blob Storage Writer following the object storage organization.
- Add the corresponding documentation

### Tests

I wasn't sure on how to implement tests for a writer like that. If you have any idea it would be great. Also, it should work but I don't have any credential to really test it so if you have some or know someone who does, mp me.

### Documentation

My PR adds documentation that describes how to use it.

### CODE REVIEW

**Review by bibimorlet — APPROVED** [review]

**Comment by bibimorlet** [comment]
Nice!
Need to test it on an Azure Cloud. I'll try to find an Azure project in order to try it

**Comment by pol-defont-reaulx** [comment]
Ok thanks!!
I'll merge it after these tests then

**Comment by bibimorlet** [comment]
Seems to be working 👍 
I'll resolve conflicts

**Comment by pol-defont-reaulx** [comment]
Ok thanks ;)

**Pull request merged**
