### PR TITLE
ACK v2.0

### PR DESCRIPTION
**Pull request by gabrielleberanger**
# New Release: ACK v2.0

This new release is implementing the following enhancements/features:

:new: **Change of the application name**
From NCK (Nautilus Connectors Kit) to ACK (Artefactory Connectors Kit)

:new: **Creation of a Sphinx documentation**
https://artefactory.github.io/artefactory-connectors-kit/

:new: **Update of the previous entrypoint**
from `python nck/entrypoint.py <READER_COMMAND> <WRITER_COMMAND>` to `python ack/entrypoints/cli/main.py <READER_COMMAND> <WRITER_COMMAND>`

:new: **Creation of a new entrypoint accepting a configuration .json as an input**
`python ack/entrypoints/json/main.py --config-file <PATH/TO/FILE>`

:new: **Add of date checks**
Verifying the coherence between the start-date, end-date and date-range options provided by the end user

:new: **Add of a predefined date-range option for sources that are not offering it by default** 
Available values: `YESTERDAY`, `LAST_7_DAYS`, `PREVIOUS_WEEK`, `PREVIOUS_MONTH`, `LAST_90_DAYS`. Impacted sources: Adobe Analytics, Google DCM, Google SA360, Google Search Console, MyTarget, The Trade Desk, Twitter.

:new: **Standardization of key normalization behaviors**
Keys are not normalized by default anymore - if you wish to normalize them, you should set the normalize-keys option to true: `python ack/entrypoints/cli/main.py --normalize-keys true <READER_COMMAND> <WRITER_COMMAND>`

:new: **(Transparent to end-users) In-depth refactoring of repo architecture**

---

### Readers

- **Analytics**
    - Adobe Analytics 1.4
    - Adobe Analytics 2.0
    - Google Analytics
- **Advertising - Adserver**
    - Google Campaign Manager
- **Advertising - DSP**
    - Google Display & Video 360
    - The Trade Desk
- **Advertising - Search**
    - Google Ads
    - Google Search Ads 360
    - Google Search Console
    - Yandex Campaign
    - Yandex Statistics
- **Advertising - Social**
    - Facebook Marketing
    - MyTarget
    - Radarly
    - Twitter Ads
- **CRM**
    - SalesForce
- **Databases**
    - MySQL
- **DevTools**
    - Confluence
- **Files (.csv, .njson)**
    - Amazon S3
    - Google Cloud Storage
    - Google Sheets

### Writers

- **Data Warehouses**
    - Google BigQuery
- **Debugging**
    - Console
- **Files (.njson)**
    - Amazon S3
    - Google Cloud Storage
    - Local file

### CODE REVIEW

**Review by benoitgoujon — COMMENTED** [review]
Hm is it v2 or v1.3? 🤔

**Comment by gabrielleberanger** [comment]
> Hm is it v2 or v1.3? 🤔

I would go for v2 as we changed the name of the app and the entrypoints, which is quite a big evolution. But I am keen to hear your arguments if you think that v1.3 would be more suitable ! 😊

**Comment by benoitgoujon** [comment]
this is because I've seen v1.3 in the `.env` file. I would also prefer a v2.

**Comment by gabrielleberanger** [comment]
> this is because I've seen v1.3 in the `.env` file. I would also prefer a v2.

Indeed, you have a sharp eye! Just created a mini-PR to update it

**Review by bibimorlet — APPROVED** [review]

**Pull request merged**
